### ISSUE TITLE
UI issues with recent commits

### ISSUE THREAD

**Issue by fietser28** [eez-open/studio#394]
**Describe the bug**
Commit [https://github.com/eez-open/studio/commit/26edf14356bdf3a423f0e5640ef0b6275f0fee98](https://github.com/eez-open/studio/commit/26edf14356bdf3a423f0e5640ef0b6275f0fee98) introduced some strange UI behaviours: 
- adding a new action to a dashboard project by dropping it on the screen canvas: the alignment lines stay present after releasing the action. The object on the canvas appears frozen.

**To Reproduce**
1. Open a dashboard project
2. drag a new action or widget on the canvas
3. Canvas is 'frozen' / scrambled 

Other case:
1. Open a LVGL project
2. drag a new action on the canvas
3. new action is displayed malformed and frozen.

**Expected behavior**
As before commit.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 14.2.1

**Additional context**
Reverting back before this commit everything works.

**Comment by mvladic** [comment]
Fixed!

**Comment by fietser28** [comment]
In dashboards it seems fixed. In LVGL project I still see strange behaviour:
<img width="814" alt="image" src="https://github.com/eez-open/studio/assets/8796121/a7c43b9a-c8db-4786-a9cf-c17639572d3e">

These are newly created actions. Existing actions/widget seem fine.

**Comment by mvladic** [comment]
Fixed.

**Comment by fietser28** [comment]
Just dit a duplicate of a label and this showed up:
<img width="814" alt="image" src="https://github.com/eez-open/studio/assets/8796121/2db8222c-a3fc-44fe-b179-e5bdad82efd1">

When moving the new label inside the screen in the widget structure the label contents stil won't show:
<img width="814" alt="image" src="https://github.com/eez-open/studio/assets/8796121/e280aef3-7dbd-4419-b4a5-ae37fc5f8425">

After removing the ' weird displayed actions' in the comment above, all widgets suddenly started working:
<img width="1116" alt="image" src="https://github.com/eez-open/studio/assets/8796121/1098c575-ea86-4a7d-87eb-6360d0e55c9f">

This is consistent if I reproduce this: Adding a new ACTION the action shows up weird and widget start behaving weird. After deletion of the new action everything is normal again.

**I was typing this while you fixed this, so will test first..**

**Comment by fietser28** [comment]
Dit tests. Most use cases from my last comments are fixed now.

Only 1 stil remains: When I duplicate a widget (right click with mouse on original and select duplicate) it shows up wrong:
<img width="644" alt="image" src="https://github.com/eez-open/studio/assets/8796121/c5608bd7-5732-4ba4-bcb7-ca8ed0851356">

Dragging it into the screen in widget structure fixes it again.

**Comment by mvladic** [comment]
Fixed.

**Comment by fietser28** [comment]
All fine now!
