### ISSUE TITLE
Cannot customize tab headers

### ISSUE THREAD

**Issue by dmitrij9992905** [eez-open/studio#841]
Hello everyone!

I'm trying to customize tab view, and I cannot find any parameters what is in charge of tab headers style
How can I customize them?

For example, make them transparent

<img width="402" height="629" alt="Image" src="https://github.com/user-attachments/assets/bcda1c5f-e8d3-4f6e-8b96-5e90e8731ac0" />

**Comment by maxtong2012213** [comment]
go to style and find back ground and set the opacity lower .


<img width="611" height="745" alt="Image" src="https://github.com/user-attachments/assets/9d3ebe2d-4587-4ef7-9932-88ba4141c31a" />

**Comment by dmitrij9992905** [comment]
I use EEZStudio v0.23.2
I tried to find the property, but it has effect just on tab contains and not on tab header
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/ceba10c9-425a-404e-a253-92c3778ba5bd" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/71cd73f9-b845-4d0b-99d2-644bc44ffe9e" />

**Comment by mvladic** [comment]
Check the Styled Tabview example:

<img width="807" height="156" alt="Image" src="https://github.com/user-attachments/assets/1aedf760-4b91-4718-afa9-954dcc111cee" />

Just add two Container widgets as children to the Tabivew. These container widgets will be for the Bar and Content part. Inside Content you can add Tab widgets:

<img width="1310" height="468" alt="Image" src="https://github.com/user-attachments/assets/b2503a72-c4fe-45a2-8589-df620224389f" />

Then you can modify styles of the Bar widget.

**Comment by JiayunLi-3E8** [comment]
> Check the Styled Tabview example:
> 
> <img alt="Image" width="807" height="156" src="https://private-user-images.githubusercontent.com/449788/483606005-1aedf760-4b91-4718-afa9-954dcc111cee.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc0OTkwNDMsIm5iZiI6MTc1NzQ5ODc0MywicGF0aCI6Ii80NDk3ODgvNDgzNjA2MDA1LTFhZWRmNzYwLTRiOTEtNDcxOC1hZmE5LTk1NGRjYzExMWNlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkxMFQxMDA1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmE5YjVkN2Y2ZmM0ODRhZmRkNTQyNDE4ZWRlZjgyMWM3MmIzNWM4NTlmMTk0NjU1ZmU4Y2U2ZWQ5NDljMTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iYM_Ax0aPmvy6NAlnwd9ny8cNLa73zBH3i0FxovchFQ">
> Just add two Container widgets as children to the Tabivew. These container widgets will be for the Bar and Content part. Inside Content you can add Tab widgets:
> 
> <img alt="Image" width="1310" height="468" src="https://private-user-images.githubusercontent.com/449788/483606511-b2503a72-c4fe-45a2-8589-df620224389f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc0OTkwNDMsIm5iZiI6MTc1NzQ5ODc0MywicGF0aCI6Ii80NDk3ODgvNDgzNjA2NTExLWIyNTAzYTcyLWM0ZmUtNDVhMi04NTg5LWRmNjIwMjI0Mzg5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkxMFQxMDA1NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTY1OWJiZDU5YTVmMTE5NTgxZTVhMjQ3MjM3ZDViYTQwNTVhNmQwNzA5Njk4ZWRiNjkwNWVjNzJiNWIzNGFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wnL5Ryb-0r94rFT9KRew3LYEl_Se-rJMocTho0GGRjM">
> Then you can modify styles of the Bar widget.

But, How to change the color or style of the active tab, like this blue of the "Tab1"? @mvladic

**Comment by quanghona** [comment]
According to the Styled Tabview example, I will summarize how we can modify the tabview, Bar container:

- To change the background of the non-active tab(s): to **style -> Main part -> DEFAULT -> BACKGROUND** properties, you can change the color, opacity...
- To change the text of the non-active tab(s): to **style -> Main part -> DEFAULT -> TEXT**. Change the properties of the text.
- To change the background of the active tab: to **style -> Items part -> CHECKED -> BACKGROUND** then change the properties such as Color, Opacity
- To change the text of the active tab, similarly: to **style -> Items part -> CHECKED -> TEXT**
- To change the active tab underline indicator: to **style -> Items part -> CHECKED -> BORDER**

Good luck!

**Comment by JiayunLi-3E8** [comment]
> According to the Styled Tabview example, I will summarize how we can modify the tabview, Bar container:
> 
> * To change the background of the non-active tab(s): to **style -> Main part -> DEFAULT -> BACKGROUND** properties, you can change the color, opacity...
> * To change the text of the non-active tab(s): to **style -> Main part -> DEFAULT -> TEXT**. Change the properties of the text.
> * To change the background of the active tab: to **style -> Items part -> CHECKED -> BACKGROUND** then change the properties such as Color, Opacity
> * To change the text of the active tab, similarly: to **style -> Items part -> CHECKED -> TEXT**
> * To change the active tab underline indicator: to **style -> Items part -> CHECKED -> BORDER**
> 
> Good luck!

The part of 'active' is not working. See the picture below. By the way, I am using v0.24.0.

<img width="1920" height="905" alt="Image" src="https://github.com/user-attachments/assets/0134755d-4de5-4bef-9aab-f4c3348a6295" />

**Comment by arturv2000** [comment]
The issue is related to the LVGL Version selected for the project.

The example project works as long the LVGL version is `8.x`, if change to `9.x` the `border` side change it no longer works.

**Comment by quanghona** [comment]
Yeah, I experienced the same issue. With the same configuration, version 9.x does not work but 8.x do. And I noticed that, version 9.x don't have Ticks part.

**Comment by Akniaaaaaa** [comment]
how add icon di container bar in tab view ?

**Comment by mvladic** [comment]
Fixed. Customization of tab headers now works in LVGL version 9.x the same way it works in version 8.x, see [the following comment](https://github.com/eez-open/studio/issues/841#issuecomment-3236793009).

**Comment by thisisrandy** [comment]
Talk about [a quick response](https://github.com/eez-open/studio/issues/1007)! However, I'm afraid there's still an issue. I just cloned and built the repo per the readme instructions on Ubuntu 26.04. At first glance, the Styled Tabview example works perfectly when targeting LVGL 9.x. However, when I open my project, which uses a project style to control the "Items part -> CHECKED" styling, changes to the project style are *not* reflected in the widget. Specifically, when I look at the widget's styling, changes to the project style appear in the value box, but they must be manually enabled instead of being automatically reflected the way I understand project styles to work. I tried randomly editing some other project style in the same project (button styling, in this case), and my changes were immediately reflected on the widgets using it, so there's a clear discrepancy.

**Comment by mvladic** [comment]
Thanks for reporting that issue too! It should be fixed now.

**Comment by thisisrandy** [comment]
Confirmed fixed on both counts. Obviously I can just build the repo for now, but when can we expect to see this in a release? Thanks very much for your quick work 😀.

**Comment by mvladic** [comment]
We are planning to release it in a week or two. There are some PR's waiting to be reviewed and merged and after that we will release it.
